-- Insert unique annotation categories.
INSERT OR IGNORE INTO annotation_categories (category_label, label, description) VALUES
    ('MOL', 'Molecule names', 'The MOL entity covers molecular compounds, including simple molecules, ions, nucleic acids, proteins, lipids, sugars, polymers, and complexes. MOL entities should be uniquely identifiable.'),
    ('SOFTNAME', 'Software names', 'The SOFTNAME entity refers to the name of any software used for molecular simulation, visualization, or analysis. It includes packages for molecular dynamics, modeling, trajectory processing, and any other computational tasks relevant to the simulation workflow.'),
    ('SOFTVER', 'Software versions', 'The SOFTVERS entity refers to the version identifier of any software used in the simulation process. It includes version numbers, release tags, or labels, regardless of formatting (e.g., numeric, date-based, semantic).'),
    ('FFM', 'Forcefield or model', 'The FFM entity refers to any force field or molecular model used to describe the interactions between particles in a simulation. This includes all classical all-atom force fields, coarse-grained models, solvent models, and water models. Both the name and version of the force field/model are relevant and should be annotated when available.'),
    ('STIME', 'Simulation time', 'The STIME entity refers to the duration for which a production molecular dynamics simulation is run.'),
    ('STEMP', 'Simulation temperature', 'The STEMP entity refers to the thermal conditions under which a simulation is conducted. It includes any explicitly stated temperature values, with or without units.'),
    ('NATOM', 'Total_atoms', 'The NATOM entity refers to the total number of atoms present in the molecular system being simulated. This includes all atoms in the solute, solvent, and any other components of the system.'),
    ('STIMESTEP', 'Simulation time step', 'The STIMESTEP entity refers to the discrete time interval used in molecular dynamics simulations to advance the system state. It is typically expressed in femtoseconds (fs).');

-- Insert unique annotation provenances.
INSERT OR IGNORE INTO annotation_provenances (provenance_label, comment) VALUES
    ('Manually_annotated', 'This annotation was manually curated by a human annotator.'),
    ('Provided_by_database', 'This annotation was provided by the original database or data source.'),
    ('Extracted_automatically', 'This annotation was extracted automatically by Artificial Intelligence.');

-- Insert reference file types
INSERT OR IGNORE INTO file_types (file_type_label, comment) VALUES
    ('7z', '7-Zip compressed file format.'),
    ('bz2', 'Bzip2 compressed file format.'),
    ('cfg', 'Configuration file for simulation or analysis tools.'),
    ('cpt', 'GROMACS checkpoint file.'),
    ('csv', 'Comma-separated values file.'),
    ('dat', 'Generic data file, often used for simulation output.'),
    ('dcd', 'CHARMM/NAMD trajectory file format.'),
    ('densitiesinfo', 'Density calculation summary or information file.'),
    ('docx', 'Microsoft Word document file.'),
    ('dump', 'LAMMPS trajectory or atom dump file.'),
    ('edr', 'GROMACS energy file.'),
    ('f', 'Fortran source code or binary output file.'),
    ('ff19SB', 'AMBER force field configuration file or model reference.'),
    ('gp', 'Gnuplot script or data plotting file.'),
    ('gro', 'GROMACS structure file containing coordinates.'),
    ('gz', 'Gzip compressed file format.'),
    ('h5', 'HDF5 hierarchical data format file.'),
    ('ino', 'Arduino sketch source file or simulation input script.'),
    ('inp', 'Input configuration script for molecular dynamics packages.'),
    ('inpcrd', 'AMBER input coordinate file.'),
    ('itp', 'GROMACS include topology file.'),
    ('job', 'Batch job execution file for HPC schedulers.'),
    ('jobscript', 'HPC cluster job launcher script (e.g., Slurm/PBS).'),
    ('jpg', 'JPEG image file format.'),
    ('json', 'Structured JSON data file.'),
    ('lammps_eq16', 'LAMMPS equilibration output/parameter file.'),
    ('lammps_eq18', 'LAMMPS equilibration output/parameter file.'),
    ('lammps_eq2', 'LAMMPS equilibration output/parameter file.'),
    ('lammps_eq41', 'LAMMPS equilibration output/parameter file.'),
    ('lammps_eq43', 'LAMMPS equilibration output/parameter file.'),
    ('lammps_eq44', 'LAMMPS equilibration output/parameter file.'),
    ('lammps_eq50', 'LAMMPS equilibration output/parameter file.'),
    ('lammps_eq7', 'LAMMPS equilibration output/parameter file.'),
    ('lammps_fit3', 'LAMMPS fitting output/parameter file.'),
    ('lammps_fit59', 'LAMMPS fitting output/parameter file.'),
    ('log', 'Log file containing execution or simulation logs.'),
    ('md5', 'MD5 checksum hash file.'),
    ('mdp', 'GROMACS run input parameter file.'),
    ('mut', 'Mutational state file or structural mutation description.'),
    ('nb', 'Non-bonded interaction parameter file or Mathematica notebook.'),
    ('nc', 'NetCDF scientific data format file.'),
    ('nv', 'State variable file or custom simulation parameter.'),
    ('par', 'CHARMM/AMBER force field parameter file.'),
    ('pb', 'Protocol Buffer or Poisson-Boltzmann calculations file.'),
    ('pbs', 'PBS cluster scheduler job script.'),
    ('pdf', 'Portable Document Format file.'),
    ('pdb', 'Protein Data Bank coordinate file.'),
    ('pK_decomposition', 'pKa calculation breakdown or decomposition output.'),
    ('png', 'Portable Network Graphics image file format.'),
    ('pptx', 'Microsoft PowerPoint presentation file.'),
    ('prmtop', 'AMBER parameter/topology file.'),
    ('psf', 'Protein Structure File used in CHARMM/NAMD simulations.'),
    ('restrt', 'AMBER/CHARMM restart coordinate file.'),
    ('sdf', 'Structure-Data File format for chemical compounds.'),
    ('smi', 'SMILES chemical structure representation file.'),
    ('span', 'Spatial constraint or spanning tree output file.'),
    ('str', 'CHARMM stream topology and parameter file.'),
    ('svg', 'Scalable Vector Graphics image file format.'),
    ('tar', 'Tape Archive file format for bundling files.'),
    ('tdb', 'GROMACS trajectory database file.'),
    ('tbl', 'Tabular data file or restraint table.'),
    ('top', 'Topology input file.'),
    ('tpr', 'GROMACS portable run input file.'),
    ('trj', 'Generic trajectory file format.'),
    ('trr', 'GROMACS full-precision trajectory file.'),
    ('tsv', 'Tab-separated values file.'),
    ('txt', 'Plain text file or documentation.'),
    ('variables', 'Simulation environment variable definition file.'),
    ('vmd', 'VMD state, visualization script, or project file.'),
    ('xml', 'Extensible Markup Language file.'),
    ('xlsx', 'Microsoft Excel spreadsheet file.'),
    ('xsc', 'NAMD extended system configuration/restart file.'),
    ('xtc', 'GROMACS compressed trajectory file.'),
    ('xtxt', 'Formatted plain text document or extended log file.'),
    ('xvg', 'GROMACS xmgrace plot data file.'),
    ('zip', 'Compressed archive file containing multiple files.');



-- Insert reference molecule types
INSERT OR IGNORE INTO molecule_types (molecule_type_label, description) VALUES
    ('protein', 'Proteins, peptides, and amino acid chains.'),
    ('lipid', 'Lipids, fatty acids, and lipid bilayer components.'),
    ('nucleic_acid', 'DNA, RNA, and oligonucleotides.'),
    ('small_molecule', 'Ligands, drugs, cofactors, metabolites, and small organic compounds.'),
    ('carbohydrate', 'Glycosylated molecules, sugars, and polysaccharides.'),
    ('ion', 'Charged atomic or molecular species, including cations and anions.'),
    ('complex', 'Multimolecular assemblies or heterogenic complexes.'),
    ('polymer', 'Synthetic polymers, macromolecules, and non-biological chains.'),
    ('other', 'Any other molecular type not covered by the above categories.');


